version: '3.8'

services:
  php:
    container_name: jagaad_php_cli
    environment:
      PHP_IDE_CONFIG: 'serverName=localhost'
      XDEBUG_CONFIG: 'idekey=PHPSTORM'
    build:
      context: docker/php
    restart: on-failure
    volumes:
      - ".:/var/www/html"
      - "./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"